%YAML 1.2
---
# Main configuration document

llsfrb:
  plugins: "conveyor_belt"

  log:
    level: info
    general: refbox.log
    clips: clips.log
    game: game.log

  conveyor-belt:
    enable: false
    host: !ipv4 127.0.0.1
    camera_status_port: !tcp-port 55521
    conveyor_status_port: !tcp-port 55522
    command_port: !tcp-port 55523

  clips:
    dir: "@BASEDIR@/atwork/clips"
    # Timer interval, in milliseconds
    timer-interval: 40

    main: refbox
    debug: true
    # debug levels: 0 ~ none, 1 ~ minimal, 2 ~ more, 3 ~ maximum
    debug-level: 2
    unwatch-facts: [time, signal]
    unwatch-rules: [retract-time,
                    net-send-beacon, net-send-BenchmarkState, net-send-TaskInfo,
                    net-send-Inventory, net-send-VersionInfo,
                    net-send-ConveyorBeltStatus]

  comm:
    protobuf-dirs: ["@BASEDIR@/atwork/msgs"]

    server-port: !tcp-port 4444

    public-peer:
      host: !ipv4 192.168.1.255
      #port: !udp-port 4444
      send-port: !udp-port 4444
      recv-port: !udp-port 4445

    b-it-bots-peer:
      host: !ipv4 192.168.1.255
      #port: !udp-port 4446
      send-port: !udp-port 4446
      recv-port: !udp-port 4447

    smARTLab-peer:
      host: !ipv4 192.168.1.255
      #port: !udp-port 4448
      send-port: !udp-port 4448
      recv-port: !udp-port 4449

    SPQR-peer:
      host: !ipv4 192.168.1.255
      #port: !udp-port 4450
      send-port: !udp-port 4450
      recv-port: !udp-port 4451

  mongodb:
    enable: false
    hostport: localhost
    collections:
      text-log: llsfrb.log
      clips-log: llsfrb.clipslog
      protobuf: llsfrb.protobuf

  game:
    teams: [b-it-bots, smARTLab, SPQR]
    crypto-keys:
      b-it-bots: randomkey
      smARTLab: randomkey
      SPQR: randomkey

  shell:
    refbox-host: !ipv4 127.0.0.1
    refbox-port: 4444
